# Generated by Django 4.2.3 on 2023-07-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_cart_razorpayorderid_cart_razorpaypaymentsignature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='razorpayPaymrntID',
            new_name='razorpayPaymentID',
        ),
    ]
