# Generated by Django 4.2.3 on 2023-07-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0002_colorvarient_product_colorvarient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colorVarient',
            field=models.ManyToManyField(blank=True, to='MarketApp.colorvarient'),
        ),
    ]
