# Generated by Django 4.2.3 on 2023-07-22 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0003_alter_product_colorvarient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('couponCode', models.CharField(max_length=10)),
                ('isExpired', models.BooleanField(default=False)),
                ('discountPrice', models.IntegerField(default=150)),
                ('minimumAmount', models.IntegerField(default=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
